INSERT INTO public.store_config (
  id, name, slogan, whatsapp, whatsapp_message, rating, minimum_order, is_open,
  status_message, schedule_weekdays, schedule_weekends, delivery_fee, delivery_free_above,
  delivery_estimated_time, hero_image_url, logo_url, updated_at, address, instagram_url,
  facebook_url, show_address, show_instagram, show_facebook, design_bg_body, design_bg_container,
  design_color_primary, design_color_secondary, design_color_text_main, design_color_text_light,
  design_header_bg, design_header_text, design_header_badge_bg, design_header_badge_text,
  design_banner_overlay, design_banner_button_bg, design_banner_button_text, design_banner_title_color,
  design_category_bg, design_category_text, design_category_active_bg, design_category_active_text,
  design_category_border_radius, design_card_bg, design_card_title_color, design_card_description_color,
  design_price_color, design_badge_bg, design_badge_text, design_button_primary_bg, design_button_primary_text,
  design_button_secondary_bg, design_button_secondary_text, design_button_radius, design_cart_bg,
  design_cart_title_color, design_cart_border_color, design_font_family, design_title_size, design_text_size,
  design_card_radius, design_card_shadow, design_container_width, design_bg_image_url, design_alt_logo_url
) VALUES (
  'caf1490b-9144-42a4-9739-639bee74ea4b',
  'Toque de Amor confeitaria e Hamburgueria',
  'Olá, seja bem vindo ao Toque de Amor!!',
  '55219760036',
  'Olá, gostaria de fazer um pedido!',
  5.0, 15.00, true,
  '21976003669',
  '11:00 - 23:59',
  '00:00 - 23:59',
  5.00, 150.00,
  '30-50 min',
  'https://pnnmfwzlndwrohkucxyd.supabase.co/storage/v1/object/public/store-images/hero-1772417114262.jpg',
  'https://pnnmfwzlndwrohkucxyd.supabase.co/storage/v1/object/public/store-images/logo-1772417022975.png',
  '2026-03-18 02:52:23.628828+00',
  'Estrada das Agulhas Negras,335',
  'https://www.instagram.com/toquedeamor_cg?igsh=MWNzY2d1eXoxbTBveg==',
  'https://www.facebook.com/share/1AimP8t4ko/',
  true, true, true,
  '#f5f0eb', '#ffffff', '#f07c00', '#2e2e2e', '#2a2118', '#8a7e73',
  '#2e2e2e', '#fafafa', '#f07c00', '#ffffff',
  'rgba(46,46,46,0.5)', '#f07c00', '#ffffff', '#ffffff',
  '#ebe7e2', '#121212', '#2e2e2e', '#fafafa', '0.5rem',
  '#ffffff', '#2a2118', '#0e0701', '#f0000c', '#e84c3d', '#ffffff',
  '#f07c00', '#ffffff', '#2e2e2e', '#fafafa', '0.75rem',
  '#ffffff', '#2a2118', '#e5e0db',
  'Open Sans', '1.25rem', '1.125rem', '0.75rem',
  '0 1px 3px rgba(0,0,0,0.08)', '1280px', '', ''
);